<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-26T16:55:24Z" name="Default suite" finished-at="2022-07-26T16:56:13Z" duration-ms="48633">
    <groups>
    </groups>
    <test started-at="2022-07-26T16:55:24Z" name="Default test" finished-at="2022-07-26T16:56:13Z" duration-ms="48633">
      <class name="script.InvalidLogin">
        <test-method is-config="true" signature="createReport()[pri:0, instance:script.InvalidLogin@4722ef0c]" started-at="2022-07-26T16:55:24Z" name="createReport" finished-at="2022-07-26T16:55:24Z" duration-ms="309" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createReport -->
        <test-method is-config="true" signature="openApp(java.lang.reflect.Method, java.lang.String)[pri:0, instance:script.InvalidLogin@4722ef0c]" started-at="2022-07-26T16:55:24Z" name="openApp" finished-at="2022-07-26T16:55:37Z" duration-ms="13137" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void script.InvalidLogin.testInValidLogin()]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[config.properties]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testInValidLogin()[pri:1, instance:script.InvalidLogin@4722ef0c]" started-at="2022-07-26T16:55:37Z" name="testInValidLogin" finished-at="2022-07-26T16:56:11Z" duration-ms="33464" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Home Page is not Displayed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Home Page is not Displayed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at script.InvalidLogin.testInValidLogin(InvalidLogin.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInValidLogin -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.InvalidLogin@4722ef0c]" started-at="2022-07-26T16:56:11Z" name="closeApp" finished-at="2022-07-26T16:56:13Z" duration-ms="2013" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testInValidLogin status=FAILURE method=InvalidLogin.testInValidLogin()[pri:1, instance:script.InvalidLogin@4722ef0c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method is-config="true" signature="publishReport()[pri:0, instance:script.InvalidLogin@4722ef0c]" started-at="2022-07-26T16:56:13Z" name="publishReport" finished-at="2022-07-26T16:56:13Z" duration-ms="405" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- publishReport -->
      </class> <!-- script.InvalidLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
